import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Skills from '../components/skills/Skills'
import Projects from '../components/Projects'
import Footer from '../components/layout/footer/Footer'
import Header from '../components/layout/header/Header'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <article id='about'>
          <h2>About me</h2>
          <p>I'm a Frontend developer who loves simple and stylized
            designs. I am mostly self-taught and whenever
            I can try to learn new technologies.</p>
        </article>
        <Skills />
        <Projects />

      </main>

      <Footer />
    </div>
  )
}
