import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faTwitter, faLinkedin } from '@fortawesome/free-brands-svg-icons'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Skills from '../components/Skills'
import Projects from '../components/Projects'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav className={styles.nav}>
          <ul>
            <li>Home</li>
            <li>Skills</li>
            <li>Projects</li>
          </ul>
        </nav>
        <h1>
          Hello there, I am
          Agustin
        </h1>
        <h2>Frontend developer</h2>
      </header>

      <main className={styles.main}>
        <article>
          <h2>About me</h2>
          <p>I'm a Frontend developer who loves simple and stylized
            designs. I am mostly self-taught and whenever
            I can try to learn new technologies.</p>
        </article>

        <Skills />
        <Projects />
        
      </main>

      <footer className={styles.footer}>

        <div className={styles.medialinks}>
          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
          >
            <FontAwesomeIcon icon={faGithub} />
          </a>
          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
          >
            <FontAwesomeIcon icon={faTwitter} />
          </a>
          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
          >
            <FontAwesomeIcon icon={faLinkedin} />
          </a>
        </div>
        <p>
          updated 2022
        </p>
      </footer>
    </div>
  )
}
